### ISSUE TITLE
Add properly configured .gitignore file

### ISSUE THREAD

**Issue by JohnKhandygo** [ADsty/shedule#1]
В .gitignore файле описываются файлы и директории, которые необходимо исключить при работе с данным репоиторием в git. В число таких файлов, как правило, включают специфичные для пользователей файлы, что позволяет избежать конфликтов при конкурентной работе с репозиторием. В частности, сюда целесообразно отнести файлы, [генерируемые IDE](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems), поскольку их формат и содержание может отличаться от версии к версии. Для генерации .gitignore в idea удобно использовать [.ignore плагин](https://plugins.jetbrains.com/plugin/7495--ignore).

**Comment by ADsty** [comment]
Сгенерировал

**Comment by JohnKhandygo** [comment]
Замечательно, однако некоторые файлы, добавленые в `.gitignore`, присутствуют в удаленном репозитории и отслеживаются git'ом. Таким образом, любые изменения в них все равно могут попасть в репозиторий.

**Comment by JohnKhandygo** [comment]
Для окончательного избавления от всех ненужных в репозитории файлов (при условии, что они добавлены в .gitignore) можно использовать команду [git-clean](https://git-scm.com/docs/git-clean).

**Comment by ADsty** [comment]
Вроде бы все сделал правильно , однако на гит хабе отображается все как раньше

**Comment by JohnKhandygo** [comment]
Так. Мой косяк, не та команда. 
Для того, чтобы удалить файлы, которые есть в `.gitignore`, но которых не должно быть в удаленном репозитории необходимо сделать следйющее:

1. Открыть консоль (терминал, cmd) в папке с проектом:
  - Можно в обычной консоли сделать
  - Можно открыть вкладку terminal в нижней панели idea (alt + f12). Этот терминал откроется уже сразу внутри директории проекта.
2. Выполнить команду `git rm --cached`
  - Для обычных файлов `git rm --cached <path_to_file>`. 
  - Для директорий `git rm -r --cached <path_to_directory>`.
3. Далее делаем обычный коммит
  - В идее ctrl + K 
  - В консоли `git commit -m "<commit message>"`
4. Пушим изменения
  - В идее при коммите выбираем commit and push
  - В идее alt + ~ и выбираем push 
  - В консоли `git push origin master`

После этого в удаленном репозитории (то есть на github) должны пропасть все файлы, для которых был выполнен второй шаг.

**Comment by ADsty** [comment]
В консоли выдало следующее:
rm '.idea/libraries/hamcrest_core_1_3.xml' 
rm '.idea/libraries/junit_4_12__1_.xml' 
rm '.idea/misc.xml' 
rm '.idea/modules.xml' 
rm '.idea/vcs.xml'
rm 'lib/hamcrest-core-1.3.jar'
rm 'lib/junit-4.12 (1).jar'
rm 'shedule.iml'
Однако я почему то после трех попыток до сих пор вижу у себя в репозитории эти файлы

**Comment by JohnKhandygo** [comment]
Странно. Есть два варианта:
- Добавить опцию '--force' к `git rm` (то есть чтобы получилось что-то типа `git rm --cached --force <path_to_file>`).
- Второй вариант просто на шару
  - Очистить файл .gitignore
  - Выполнить `git rm` для необходимых файлов
  - Восстановить содержимое .gitignore
  - Коммит и пуш

Если ничего из этого не сработает, то закрываю это замечание.

**Comment by JohnKhandygo** [comment]
Похоже на то.
