### ISSUE TITLE
Add Javadoc

### ISSUE THREAD

**Issue by JohnKhandygo** [ADsty/shedule#2]
Добавьте javadoc к разработанным классам.

**Comment by ADsty** [comment]
Я их добавил , но один из них удалю , когда сделаю обработку исключений и дополню еще несколько

**Comment by JohnKhandygo** [comment]
По хорошему надо все публичные методы описать в javadoc. Также, помимо описания параметров и возвращаемого значения, принято давать хотя бы минимальное описания того, что метод делает. Так, например, в методе `findTrain` было бы неплохо указать, как поведеть себя функция в случае, когда есть несколько подходящих поездов, отправляющихся в одно и то же время.
