### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by JohnKhandygo** [ADsty/shedule#4]
По условиям первого задания весь разработанный код должен быть покрыт тестами. Для вычисления процента покрытия используйте [Run with Coverage](https://www.jetbrains.com/help/idea/running-with-coverage.html). От Вас, естественно, не требуется покрывать тестами такие методы, как `equals`, `hashCode` и `toString`.

**Comment by ADsty** [comment]
Тесты будут , как и все остальное , но у меня возникла по ходу создания тестов проблема , которую я очень долго искал как решить. Из-за этого работа застопорилась , и я не мог загрузить изменения в проекте , тк вообще не знал работает ли программа так , как я задумывал.

**Comment by JohnKhandygo** [comment]
Самое время задать вопросы по проблемам, которые Вы не можете решить.

**Comment by ADsty** [comment]
Сейчас обычные тесты работают , но не работает Run with Coverage. Выдает FATAL ERROR in native method: processing of -javaagent failed.

**Comment by ADsty** [comment]
Отправлю пока что на гит хаб сырой вариант класса , возможно ошибка в самом коде

**Comment by JohnKhandygo** [comment]
У меня все работает, поэтому ошибка скорее всего в настройках idea у Вас.

**Comment by ADsty** [comment]
Что ж буду пытаться починить идею

**Comment by ADsty** [comment]
Так и не смог починить идею , не могли бы Вы подсказать , как мне узнать процент покрытия , кроме как просто посмотреть сколько методов проверяют мои тесты?

**Comment by JohnKhandygo** [comment]
Только аккуратно проверить, что тесты покрывают все значимые места в коде (типа циклов, все ветки ветвлений и т.д.). Сейчас у Вас нормальное покрытие, около ста процентов.

**Comment by JohnKhandygo** [comment]
В `TrainTest` есть идентичные тесты.
