### ISSUE TITLE
Upgrade impl.

### ISSUE THREAD

**Issue by JohnKhandygo** [ADsty/shedule#5]
У Вас достаточно много сценариев использования не предусмотрено в коде:

- [x] Никакие методы не проверяют корректность входных параметров (например, формат времени, уникальность промежуточных станций и проверки на `null`).
- [x] В условии задачи сказано, что необходимо реализовать метод "поиска ближайшего по времени поезда (по станции, куда едем, и текущему времени)". В вашей реализации в методе `findTrain`  откуда-то взялся лишний параметр `currentStation`, хотя Ваша реализация (да этого и не требуется в задаче) не предусматривает хранение времени отправления с промежуточных станций. 
- [x] В Вашей реализации не предусмотрен сценарий, при котором добавляется несколько одинаковых поездов (например, один и тот же поезд может ходить несколько раз в день, но список промежуточных станций может меняться в зависимости от времени отправления).
- [x] Метод `findTrain` может вернуть несуществующий поезд, однако с программной стороны нет возможности узнать, существует ли такой поезд на самом деле. Для решения этой проблемы можно использовать, например, `Optional`. Альтернативный вариант, заключается в том, чтобы предусмотреть возвращение более одного подходящего поезда (тогда Вы бы просто возвращали пустой список).
- [x] Не понятно, почему Вы задаете время в `Train` строкой. В то же время, `getDepartureTime` возвращает `int`, однако такое представление необходимо только Вам внутри реализации, стороннему пользователю было бы удобнее работать с каким-нибудь более обобщенным представлением. В `Java` есть много классов, работающих с временм (см. [пакет java.time](https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html)), которых должно хватить для Ваших нужд.

Все эти сценарии, включая вызовы с некорректными параметрами, должны быть зафиксированы в тестах.

**Comment by ADsty** [comment]
Постарался исправить все сценарии , добавил исключения , добавил тесты для исключений и разнообразил как смог одинаковые тесты , исправил gitignore файл и добавил javadoc ко всем методам с описанием того , что они делают

**Comment by ADsty** [comment]
Изменил метод findTrain и все тесты , использующие его , а также поменял метод removeTrain , используя итератор.

**Comment by JohnKhandygo** [comment]
Замечательно. Все очень хорошо, накину какой-нибудь бонус к оценке. Осталось всего несколько замечаний:
- [ ] Поле `names` в  классе `Schedule` является публичным. Подумайте, может ли это как-то "сломать" логику Вашего класса.
- [ ] Метод `findTrain` реализован некорректно. Когда поймете в чем ошибка, хотелось бы увидеть тест, который фиксирует сценарий некорректного поведения.
- [ ] В методе `findTrain` пересчитываете одинаковые величины. Вообще не понятно, зачем Вам `p` и `x` в этом методе. 
- [ ] В тестах много копипаста там, где Вы создаете новый экземпляр `Schedule`. Решить это можно, используя специальный механизм junit (@Before)[https://junit.org/junit4/javadoc/4.12/org/junit/Before.html].

**Comment by ADsty** [comment]
Исправил ошибку в методе findTrain , убрал поезда p и x (они остались от прошлой реализации , которая возвращала поезд, а не список поездов) , перекинул создание одних и тех же обьектов из тестов в механизм @before и поменял поле names (я просто не замечал что оно было public , а не private) . По сути если бы оно было public , то пользователь мог бы добавить несуществующие или неправильно записанные поезда напрямую , обойдя проверку

**Comment by ADsty** [comment]
И так же любой пользователь мог бы менять правильно записанные поезда , прошедшие проверку , на неправильно записанные

**Comment by JohnKhandygo** [comment]
Ну да, все верно.
